# Use the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR \Fake_job_posting

# Copy the requirements file and app code to the container
COPY requirements.txt ./requirements.txt
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that Streamlit uses
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "main.py", "--server.port=8501"]